Algoritmo "circulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/09/2023
Var

    raio:real
    area:real





Inicio

    escreva ("Digite o valor do raio do circulo: ")
    leia (raio)

    area<- exp (raio,2) * 3,14159265358979323846)
    
    escreva ("AREA = ", area:10:3)




Fimalgoritmo