Algoritmo "operadora"



Var


        minutos:real
        valor:real



Inicio



       escreva ("Digite a quantidade de minutos: ")
       leia (minutos)

       se minutos <= 100.00 entao
       valor <- 50

       senao
            valor <- (minutos - 100) * 2 + 50
       fimse


       escreva ("Valor a pegar: RS",valor:4:2)

























Fimalgoritmo